-- Bu migration Supabase Dashboard üzerinden uygulanmıştır.
-- İçerik: Hazır ürünler catering tablosu ekleme
-- Tarih: 2026-02-13
-- NOT: Orijinal SQL Dashboard'dan çalıştırıldığı için dosya placeholder'dır.
