export type ViewMode = 'ORBIT' | 'FOCUS' | 'ASSEMBLE';

export interface AgentPersona {
  id: 'mevzuat' | 'maliyet' | 'teknik' | 'rekabet';
  name: string;
  subtitle: string;
  color: string; // Mantine color key
  accentHex: string;
  iconName: 'scale' | 'calculator' | 'hardhat' | 'radar';
  /** Desktop: percentage-based position in ORBIT mode */
  orbitPosition: { top?: string; bottom?: string; left?: string; right?: string };
  /** Which side of screen the agent is on (for camera shift direction) */
  side: 'left' | 'right';
  /** Stagger delay (seconds) for ASSEMBLE animation */
  assembleDelay: number;
  /** Position around center document in ASSEMBLE mode (offset from center) */
  assembleOffset: { x: number; y: number };
  mobileOrder: number;
}

export interface AgentFinding {
  label: string;
  value: string;
  severity?: 'info' | 'warning' | 'critical';
  /** AI confidence score (0-1) */
  confidence?: number;
  /** Brief reasoning from AI */
  reasoning?: string;
}

export interface AgentAnalysis {
  agentId: AgentPersona['id'];
  status: 'analyzing' | 'complete' | 'warning' | 'critical' | 'no-data';
  findings: AgentFinding[];
  riskScore: number; // 0-100
  summary: string; // One-liner for verdict report
}

export interface VerdictData {
  overallScore: number; // 0-100
  recommendation: 'gir' | 'dikkat' | 'girme';
  recommendationLabel: string;
  agents: AgentAnalysis[];
  generatedAt: string;
  /** Per-agent weight used in scoring (0-1, sums to 1) */
  weights?: Record<string, number>;
  /** Go/No-Go checklist derived from analysis data */
  checklist?: ChecklistItem[];
  /** AI reasoning for the decision */
  reasoning?: string;
  /** Strategic notes from AI */
  strategicNotes?: string;
  /** Who generated this verdict: 'ai' or 'rule' */
  generatedBy?: 'ai' | 'rule';
}

// ─── Agent Highlighting ──────────────────────────────────────

/** A text highlight generated by an agent's findings, mapped onto the document */
export interface AgentHighlight {
  agentId: AgentPersona['id'];
  /** The substring to highlight in the document */
  text: string;
  /** Mantine color key for the highlight */
  color: string;
  /** Label describing which finding produced this highlight */
  finding: string;
}

// ─── Verdict Checklist ───────────────────────────────────────

export interface ChecklistItem {
  id: string;
  label: string;
  status: 'pass' | 'fail' | 'unknown';
  detail?: string;
  severity: 'critical' | 'warning' | 'info';
}

/** Drag & Drop: snippet dropped onto an agent */
export interface SnippetDrop {
  agentId: AgentPersona['id'];
  text: string;
  timestamp: string;
}

// ─── Agent Tool Framework ───────────────────────────────────

export interface AgentTool {
  id: string;
  agentId: AgentPersona['id'];
  label: string;
  icon: string;
  description: string;
  /** Tool needs user-selected text as input */
  requiresSelection?: boolean;
  /** Priority when deadline is urgent (1 = highest) */
  urgencyPriority?: number;
}

export interface ToolExecution {
  toolId: string;
  status: 'idle' | 'generating' | 'complete' | 'error';
  input?: string;
  result?: ToolResult;
  error?: string;
  startedAt?: string;
}

export interface ToolResult {
  type: 'redline' | 'precedent' | 'draft' | 'calculation' | 'generic';
  // Redline (diff view)
  originalText?: string;
  revisedText?: string;
  explanation?: string;
  // Precedent (citation cards)
  citations?: { reference: string; summary: string; relevance: string }[];
  // Draft (letter)
  draftTitle?: string;
  draftBody?: string;
  draftDate?: string;
  addressee?: string;
  // Generic
  content?: string;
}

// ─── Orbit Ring (Attachment Hub) ─────────────────────────

export type AttachmentType = 'note' | 'document' | 'petition' | 'ai_report' | 'link' | 'contact' | 'calculation';

export interface AttachmentFile {
  id: number;
  fileName: string;
  fileUrl: string;
  fileType: string;
  fileSize: number;
}

export interface OrbitAttachment {
  id: string;
  title: string;
  type: AttachmentType;
  content: string;
  contentFormat: 'plain' | 'markdown';
  color: string;
  pinned: boolean;
  sourceAgent?: AgentPersona['id'];
  sourceToolId?: string;
  url?: string;
  files?: AttachmentFile[];
  tags?: { id: number; name: string; color: string }[];
  metadata: Record<string, unknown>;
  createdAt: string;
  updatedAt: string;
  /** true = virtual node from analysis_summary, not yet saved to DB */
  virtual?: boolean;
}

export interface AttachmentTypeConfig {
  type: AttachmentType;
  label: string;
  icon: string;
  color: string;
  description: string;
  userCreatable: boolean;
}

export interface AttachmentDetailState {
  attachmentId: string | null;
  mode: 'view' | 'edit' | 'create';
  createType?: AttachmentType;
}

// ─── Cross-Agent References ─────────────────────────────

export interface CrossReference {
  fromAgentId: AgentPersona['id'];
  toAgentId: AgentPersona['id'];
  fromFinding: string;
  impact: string;
  severity: 'info' | 'warning' | 'critical';
}

// ─── Session Persistence ────────────────────────────────

export interface SessionRecord {
  id: number;
  session_data: {
    verdictData: VerdictData | null;
    snippetDrops: SnippetDrop[];
    agentAnalyses: AgentAnalysis[];
    duration: number;
    savedAt: string;
  };
  created_at: string;
}
